In [14]:
import json
import pandas as pd
import re

In [2]:
base = './'

def read_json(name,key=None):
    name = f"{base}/{name}"
    try:
        with open(name,'r') as openfile:
            data = json.load(openfile)
            if key:
                return data[key]
            return data
    except (FileNotFoundError, KeyError)as e:
        if key:
            return []
        return {}

def write_json(data,name,key=None):
    name = f"{base}/{name}"
    if key:
        initial_data = read_json(name)
        initial_data[key] = data
        data = initial_data
    data = json.dumps(data)
    with open(name,'w') as outfile:
        outfile.write(data)


def backup_json(name):
    original = read_json(name)
    back_up =  f"{base}/{name}"
    write_json(original,back_up)

In [3]:
data = read_json('presidential_2023-02-25_v3.json')

In [4]:
rows = []
lg_wards_polling = data['lg_wards_polling']
for lg_name,lg_data in lg_wards_polling.items():
    *lg,state = lg_name.split(' - ')
    lg = ''.join(lg).split('(')
    for ward_name,ward_data in lg_data.items():
        if ward_name not in ['status','missing']:
            *ward,_ = ward_name.split(' - ')
            ward = "".join(ward).split('(')
            
            for polling_unit in ward_data:
                code,polling_name = polling_unit.split('--->')
                state_code,lg_code,ward_code,pu_code = code.split('/')
                info = [state.strip(),lg[0].strip(),ward[0].strip(),
                        state_code,lg_code,ward_code,pu_code.strip(),
                        code.strip(),polling_name.strip()]
                rows.append(info)

In [5]:
# NDOKWA WEST 

rows[0]

['DELTA',
 'NDOKWA WEST',
 'UTAGBA  OGBE',
 '10',
 '12',
 '01',
 '033',
 '10/12/01/033',
 'IN FRONT OF NEW POST OFFICE I']

In [6]:
columns = ['state','lg','ward','state_code','lg_code','ward_code','pu_code','code','location']
df = pd.DataFrame(rows,columns=columns)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176846 entries, 0 to 176845
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   state       176846 non-null  object
 1   lg          176846 non-null  object
 2   ward        176846 non-null  object
 3   state_code  176846 non-null  object
 4   lg_code     176846 non-null  object
 5   ward_code   176846 non-null  object
 6   pu_code     176846 non-null  object
 7   code        176846 non-null  object
 8   location    176846 non-null  object
dtypes: object(9)
memory usage: 12.1+ MB

In [8]:
176846 - df.shape[0]

0

In [9]:
df.ward = df.ward.apply(lambda x:x.replace('  ', ' ') )

In [21]:
df[df.state_code=='37']

,state,lg,ward,state_code,lg_code,ward_code,pu_code,code,location
59278,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,002,37/03/01/002,DAGIRI II /DAGIRI PRIMARY SCHOOL
59279,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,006,37/03/01/006,SABON-GARI III/DEMONSTRATION PRI. SCH.
59280,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,034,37/03/01/034,SABON GARI III / DEMONSTRATION PRIMARY SCHOOL
59281,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,047,37/03/01/047,GOD OWN ACADEMY SETTLEMENTS
59282,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,041,37/03/01/041,SABON GARI/JSS DEMONSTRATION.
...,...,...,...,...,...,...,...,...,...
62095,FCT,MUNICIPAL,GWAGWA,37,06,12,069,37/06/12/069,ZAUDAI ANG. FADA
62096,FCT,MUNICIPAL,GWAGWA,37,06,12,064,37/06/12/064,ANGUWAN BARAU F. DABO TIMBA SHADE
62097,FCT,MUNICIPAL,GWAGWA,37,06,12,062,37/06/12/062,SABURI I ANG. NASSARAWA PLAY GROUND
62098,FCT,MUNICIPAL,GWAGWA,37,06,12,061,37/06/12/061,SABURI II HEALTH CENTER
62099,FCT,MUNICIPAL,GWAGWA,37,06,12,081,37/06/12/081,GWAGWA 6 / ALONG JIWA MAI GORO BRIDGE

In [23]:
df[df.state=='FCT']

,state,lg,ward,state_code,lg_code,ward_code,pu_code,code,location
59278,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,002,37/03/01/002,DAGIRI II /DAGIRI PRIMARY SCHOOL
59279,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,006,37/03/01/006,SABON-GARI III/DEMONSTRATION PRI. SCH.
59280,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,034,37/03/01/034,SABON GARI III / DEMONSTRATION PRIMARY SCHOOL
59281,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,047,37/03/01/047,GOD OWN ACADEMY SETTLEMENTS
59282,FCT,GWAGWALADA,GWAGWALADA CENTRE,37,03,01,041,37/03/01/041,SABON GARI/JSS DEMONSTRATION.
...,...,...,...,...,...,...,...,...,...
62095,FCT,MUNICIPAL,GWAGWA,37,06,12,069,37/06/12/069,ZAUDAI ANG. FADA
62096,FCT,MUNICIPAL,GWAGWA,37,06,12,064,37/06/12/064,ANGUWAN BARAU F. DABO TIMBA SHADE
62097,FCT,MUNICIPAL,GWAGWA,37,06,12,062,37/06/12/062,SABURI I ANG. NASSARAWA PLAY GROUND
62098,FCT,MUNICIPAL,GWAGWA,37,06,12,061,37/06/12/061,SABURI II HEALTH CENTER
62099,FCT,MUNICIPAL,GWAGWA,37,06,12,081,37/06/12/081,GWAGWA 6 / ALONG JIWA MAI GORO BRIDGE

In [11]:

df[df.code=='04/09/04/016']

,state,lg,ward,state_code,lg_code,ward_code,pu_code,code,location
44725,ANAMBRA,EKWUSIGO,ORAIFITE II,04,09,04,016,04/09/04/016,OBOM URUDUNU I

In [13]:
df.to_csv('polling units')